version: "2.2"

volumes:
  pgdata:
    driver: local


   
services:
  postgres:
    image: "postgres:11"
    volumes:
      - ./pgdata/db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: always
    environment:
      - POSTGRES_USER=quanghuy
      - POSTGRES_PASSWORD=12345678  
      - POSTGRES_DB=montoring
    env_file:
      - ./nginxsite/.env
    
  nginxsite:
    build:
      context: ./nginxsite
      dockerfile: Dockerfile.Web
    restart: always
    volumes:
      - ./nginxsite:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - ./nginxsite/.env   
  
  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - ./redis:/data

